import { NextResponse } from 'next/server';

export async function POST(request) {
  try {
    const body = await request.json();
    const {
      elderId = '+919854012345',
      elderName = 'Prayas Dey',
      displayHonorific = 'Prayas ji',
      caregiverEmail = 'prayasdey10@gmail.com',
      caregiverName = 'Primary Caregiver',
      location = 'Guwahati, Assam',
      phone = '+919854012345',
      status = 'Mild Cognitive Support Mode',
      timestamp = new Date().toISOString(),
    } = body;

    const formattedTime = new Date(timestamp).toLocaleString('en-IN', {
      timeZone: 'Asia/Kolkata',
      dateStyle: 'full',
      timeStyle: 'medium',
    });

    const web3formsAccessKey = '41854d54-e8fe-4c26-b69f-beeac8f6fd9c';

    const warningTemplate = `
============================================================
🚨 CRITICAL EMERGENCY SOS ALERT - SAHARA COGNITIVE COMPANION
============================================================

An emergency SOS beacon was triggered by your loved one from their Sahara Elder Companion Tablet.

------------------------------------------------------------
PATIENT / ELDER DETAILS:
------------------------------------------------------------
• Elder Name:       ${elderName} (${displayHonorific})
• Contact Phone:    ${phone}
• Current Location: ${location}
• Status Mode:      ${status}
• Time of Alert:    ${formattedTime} (IST)
• Portal Status:    ACTIVE EMERGENCY BEACON

------------------------------------------------------------
CAREGIVER NOTIFIED:
------------------------------------------------------------
• Caregiver Name:   ${caregiverName}
• Connected Email:  ${caregiverEmail}

------------------------------------------------------------
⚠️ RECOMMENDED IMMEDIATE ACTIONS:
------------------------------------------------------------
1. CALL YOUR LOVED ONE IMMEDIATELY at ${phone}.
2. Check their live dashboard & recent routine log on Sahara:
   https://sahara-lac.vercel.app/caregiver-dashboard
3. If no response, notify local residential staff or emergency services.

------------------------------------------------------------
Automated High-Priority Alert generated by Sahara Elderly Care.
Access Key: ${web3formsAccessKey}
============================================================
`.trim();

    // Attempt direct dispatch to Web3Forms
    let web3formsSuccess = false;
    let web3formsResponse = null;

    try {
      const payload = {
        access_key: web3formsAccessKey,
        subject: `🚨 EMERGENCY SOS ALERT: ${elderName} needs immediate assistance!`,
        from_name: 'Sahara Emergency Beacon',
        name: `${elderName} (${displayHonorific})`,
        email: caregiverEmail,
        replyto: caregiverEmail,
        to_email: caregiverEmail,
        Emergency_Level: 'CRITICAL - IMMEDIATE ACTION REQUIRED',
        Elder_Name: `${elderName} (${displayHonorific})`,
        Elder_Phone: phone,
        Current_Location: location,
        Alert_Time: formattedTime,
        Caregiver_Email: caregiverEmail,
        Caregiver_Name: caregiverName,
        Status: status,
        message: warningTemplate,
      };

      const w3res = await fetch('https://api.web3forms.com/submit', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          'Accept': 'application/json',
        },
        body: JSON.stringify(payload),
      });

      const w3data = await w3res.json().catch(() => null);
      if (w3res.ok && w3data?.success) {
        web3formsSuccess = true;
        web3formsResponse = w3data;
      }
    } catch (w3err) {
      console.warn('Web3Forms server dispatch note:', w3err.message);
    }

    return NextResponse.json({
      success: true,
      web3formsSuccess,
      timestamp: formattedTime,
      elderName,
      caregiverEmail,
      message: 'Emergency SOS alert registered and dispatched.',
    });
  } catch (err) {
    console.error('Error processing SOS alert:', err);
    return NextResponse.json(
      { success: false, error: err.message || 'Failed to dispatch SOS alert' },
      { status: 500 }
    );
  }
}
